name: workflow-example-1 

on : push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: "Welcome Message"
              run : echo "Welcome From A UBUNTU LATEST VM , THIS IS MY FIRST WORKFLOW"

            - name: "list files"
              run: ls -al

            - name: "Read File"
              run: cat README.md